### ISSUE TITLE
Przepisanie zadań do Github Issues

### ISSUE THREAD

**Issue by AdrianKokot** [AdrianKokot/put-sorting-madness#8]
Przepisanie zadań do Github Issues

---
Skonfigurowano środowisko do zarządzania rejestrem produktu i rejestrem sprintu, prowadzący ma do niego dostęp (np. Github Issues, Github Projects, Trello)

**Comment by mudziok** [comment]
Imo git przepisane bo board się świeci jak choinka :) 
![f1ff79c2cff1d151c540944305eef758](https://user-images.githubusercontent.com/69046668/205713483-03a2d073-ed30-4b50-b2b5-0ce2084b7507.jpg)
